# Impor Beberapa Package

In [1]:
from netCDF4 import Dataset
import wrf

# Direktori WRF

In [2]:
wrf_path = '/home/absen/WRF-Model/WRF/test/em_real'

# Buka salah satu file `wrfout*`

In [ ]:
wrf_d03 = Dataset(f"{wrf_path}/wrfout_d03_2022-01-01_00:00:00")
wrf_d03

# Mengetahui Variabel di dalam file `wrfout_d03`

In [ ]:
wrf_d03.variables

# Mengambil Variabel `T2` untuk semua waktu simulasi

In [6]:
wrf_t2 = wrf.getvar(wrf_d03, "T2", timeidx=wrf.ALL_TIMES)
wrf_t2

<xarray.DataArray 'T2' (Time: 67, south_north: 45, west_east: 45)>
array([[[296.03735, 295.93018, 295.8228 , ..., 293.6441 , 293.67245,
         293.704  ],
        [296.10065, 295.99606, 295.8913 , ..., 293.7721 , 293.80023,
         293.83148],
        [296.1664 , 296.0645 , 295.9624 , ..., 293.90424, 293.93213,
         293.96304],
        ...,
        [299.0425 , 299.03427, 299.026  , ..., 299.06165, 299.07745,
         299.0939 ],
        [299.09784, 299.0905 , 299.08313, ..., 299.13727, 299.15283,
         299.16898],
        [299.15347, 299.147  , 299.1405 , ..., 299.21198, 299.2273 ,
         299.2431 ]],

       [[298.4435 , 298.11072, 297.91876, ..., 301.08795, 301.07925,
         301.06866],
        [299.0005 , 298.78503, 298.64114, ..., 300.97552, 300.976  ,
         300.97687],
        [299.59412, 299.44778, 299.25894, ..., 300.87952, 300.8884 ,
         300.89532],
...
        [297.22205, 297.13092, 297.44507, ..., 299.3581 , 299.27417,
         299.33783],
        [297.36365, 297.50635, 298.319  , ..., 299.84238, 299.8306 ,
         299.7691 ],
        [298.36987, 298.38516, 298.40826, ..., 299.8995 , 299.89932,
         299.8931 ]],

       [[293.44705, 293.90994, 293.145  , ..., 300.51788, 300.47015,
         300.4254 ],
        [294.8167 , 294.67487, 294.8267 , ..., 300.62946, 300.58246,
         300.50577],
        [295.13223, 295.29224, 295.33887, ..., 300.72113, 300.67203,
         300.593  ],
        ...,
        [296.99423, 296.91522, 297.19678, ..., 299.2298 , 299.2011 ,
         299.28018],
        [297.1137 , 297.2775 , 298.08566, ..., 299.9093 , 299.92917,
         299.8426 ],
        [298.11945, 298.1327 , 298.1781 , ..., 299.99487, 300.00677,
         300.00406]]], dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 112.4 112.4 112.5 ... 113.2 113.2
    XLAT     (south_north, west_east) float32 -7.643 -7.643 ... -6.852 -6.852
    XTIME    (Time) float32 0.0 60.0 120.0 180.0 ... 3.84e+03 3.9e+03 3.96e+03
  * Time     (Time) datetime64[ns] 2022-01-01 ... 2022-01-03T18:00:00
Dimensions without coordinates: south_north, west_east
Attributes:
    FieldType:    104
    MemoryOrder:  XY 
    description:  TEMP at 2 M
    units:        K
    stagger:      
    coordinates:  XLONG XLAT XTIME
    projection:   Mercator(stand_lon=1.0000000200408773e+20, moad_cen_lat=-7....

# Mengambil Variabel Waktu

In [24]:
wrf_time = wrf.getvar(wrf_d03, 'times', timeidx=wrf.ALL_TIMES)
wrf_time

<xarray.DataArray 'times' (Time: 67)>
array(['2022-01-01T00:00:00.000000000', '2022-01-01T01:00:00.000000000',
       '2022-01-01T02:00:00.000000000', '2022-01-01T03:00:00.000000000',
       '2022-01-01T04:00:00.000000000', '2022-01-01T05:00:00.000000000',
       '2022-01-01T06:00:00.000000000', '2022-01-01T07:00:00.000000000',
       '2022-01-01T08:00:00.000000000', '2022-01-01T09:00:00.000000000',
       '2022-01-01T10:00:00.000000000', '2022-01-01T11:00:00.000000000',
       '2022-01-01T12:00:00.000000000', '2022-01-01T13:00:00.000000000',
       '2022-01-01T14:00:00.000000000', '2022-01-01T15:00:00.000000000',
       '2022-01-01T16:00:00.000000000', '2022-01-01T17:00:00.000000000',
       '2022-01-01T18:00:00.000000000', '2022-01-01T19:00:00.000000000',
       '2022-01-01T20:00:00.000000000', '2022-01-01T21:00:00.000000000',
       '2022-01-01T22:00:00.000000000', '2022-01-01T23:00:00.000000000',
       '2022-01-02T00:00:00.000000000', '2022-01-02T01:00:00.000000000',
       '2022-01-02T02:00:00.000000000', '2022-01-02T03:00:00.000000000',
       '2022-01-02T04:00:00.000000000', '2022-01-02T05:00:00.000000000',
       '2022-01-02T06:00:00.000000000', '2022-01-02T07:00:00.000000000',
       '2022-01-02T08:00:00.000000000', '2022-01-02T09:00:00.000000000',
       '2022-01-02T10:00:00.000000000', '2022-01-02T11:00:00.000000000',
       '2022-01-02T12:00:00.000000000', '2022-01-02T13:00:00.000000000',
       '2022-01-02T14:00:00.000000000', '2022-01-02T15:00:00.000000000',
       '2022-01-02T16:00:00.000000000', '2022-01-02T17:00:00.000000000',
       '2022-01-02T18:00:00.000000000', '2022-01-02T19:00:00.000000000',
       '2022-01-02T20:00:00.000000000', '2022-01-02T21:00:00.000000000',
       '2022-01-02T22:00:00.000000000', '2022-01-02T23:00:00.000000000',
       '2022-01-03T00:00:00.000000000', '2022-01-03T01:00:00.000000000',
       '2022-01-03T02:00:00.000000000', '2022-01-03T03:00:00.000000000',
       '2022-01-03T04:00:00.000000000', '2022-01-03T05:00:00.000000000',
       '2022-01-03T06:00:00.000000000', '2022-01-03T07:00:00.000000000',
       '2022-01-03T08:00:00.000000000', '2022-01-03T09:00:00.000000000',
       '2022-01-03T10:00:00.000000000', '2022-01-03T11:00:00.000000000',
       '2022-01-03T12:00:00.000000000', '2022-01-03T13:00:00.000000000',
       '2022-01-03T14:00:00.000000000', '2022-01-03T15:00:00.000000000',
       '2022-01-03T16:00:00.000000000', '2022-01-03T17:00:00.000000000',
       '2022-01-03T18:00:00.000000000'], dtype='datetime64[ns]')
Dimensions without coordinates: Time
Attributes:
    description:  model times [np.datetime64]

# Mendapatkan nilai koordinat (Latitude dan Longitude)

In [26]:
wrf_lons = wrf.getvar(wrf_d03, 'longitude')
wrf_lats = wrf.getvar(wrf_d03, 'latitude')

In [27]:
wrf_lons

<xarray.DataArray 'XLONG' (south_north: 45, west_east: 45)>
array([[112.42384 , 112.441986, 112.46012 , ..., 113.185616, 113.20375 ,
        113.22189 ],
       [112.42384 , 112.441986, 112.46012 , ..., 113.185616, 113.20375 ,
        113.22189 ],
       [112.42384 , 112.441986, 112.46012 , ..., 113.185616, 113.20375 ,
        113.22189 ],
       ...,
       [112.42384 , 112.441986, 112.46012 , ..., 113.185616, 113.20375 ,
        113.22189 ],
       [112.42384 , 112.441986, 112.46012 , ..., 113.185616, 113.20375 ,
        113.22189 ],
       [112.42384 , 112.441986, 112.46012 , ..., 113.185616, 113.20375 ,
        113.22189 ]], dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 112.4 112.4 112.5 ... 113.2 113.2
    XLAT     (south_north, west_east) float32 -7.643 -7.643 ... -6.852 -6.852
    Time     datetime64[ns] 2022-01-01
Dimensions without coordinates: south_north, west_east
Attributes:
    FieldType:    104
    MemoryOrder:  XY 
    description:  LONGITUDE, WEST IS NEGATIVE
    units:        degree_east
    stagger:      
    coordinates:  XLONG XLAT
    projection:   Mercator(stand_lon=1.0000000200408773e+20, moad_cen_lat=-7....

In [28]:
wrf_lats

<xarray.DataArray 'XLAT' (south_north: 45, west_east: 45)>
array([[-7.6431656, -7.6431656, -7.6431656, ..., -7.6431656, -7.6431656,
        -7.6431656],
       [-7.6251907, -7.6251907, -7.6251907, ..., -7.6251907, -7.6251907,
        -7.6251907],
       [-7.607216 , -7.607216 , -7.607216 , ..., -7.607216 , -7.607216 ,
        -7.607216 ],
       ...,
       [-6.88752  , -6.88752  , -6.88752  , ..., -6.88752  , -6.88752  ,
        -6.88752  ],
       [-6.8695145, -6.8695145, -6.8695145, ..., -6.8695145, -6.8695145,
        -6.8695145],
       [-6.851509 , -6.851509 , -6.851509 , ..., -6.851509 , -6.851509 ,
        -6.851509 ]], dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 112.4 112.4 112.5 ... 113.2 113.2
    XLAT     (south_north, west_east) float32 -7.643 -7.643 ... -6.852 -6.852
    Time     datetime64[ns] 2022-01-01
Dimensions without coordinates: south_north, west_east
Attributes:
    FieldType:    104
    MemoryOrder:  XY 
    description:  LATITUDE, SOUTH IS NEGATIVE
    units:        degree_north
    stagger:      
    coordinates:  XLONG XLAT
    projection:   Mercator(stand_lon=1.0000000200408773e+20, moad_cen_lat=-7....

# Membuat Plot Spasial

In [22]:
wrf.getvar(wrf_d03, "times", timeidx=wrf.ALL_TIMES)

<xarray.DataArray 'times' (Time: 67)>
array(['2022-01-01T00:00:00.000000000', '2022-01-01T01:00:00.000000000',
       '2022-01-01T02:00:00.000000000', '2022-01-01T03:00:00.000000000',
       '2022-01-01T04:00:00.000000000', '2022-01-01T05:00:00.000000000',
       '2022-01-01T06:00:00.000000000', '2022-01-01T07:00:00.000000000',
       '2022-01-01T08:00:00.000000000', '2022-01-01T09:00:00.000000000',
       '2022-01-01T10:00:00.000000000', '2022-01-01T11:00:00.000000000',
       '2022-01-01T12:00:00.000000000', '2022-01-01T13:00:00.000000000',
       '2022-01-01T14:00:00.000000000', '2022-01-01T15:00:00.000000000',
       '2022-01-01T16:00:00.000000000', '2022-01-01T17:00:00.000000000',
       '2022-01-01T18:00:00.000000000', '2022-01-01T19:00:00.000000000',
       '2022-01-01T20:00:00.000000000', '2022-01-01T21:00:00.000000000',
       '2022-01-01T22:00:00.000000000', '2022-01-01T23:00:00.000000000',
       '2022-01-02T00:00:00.000000000', '2022-01-02T01:00:00.000000000',
       '2022-01-02T02:00:00.000000000', '2022-01-02T03:00:00.000000000',
       '2022-01-02T04:00:00.000000000', '2022-01-02T05:00:00.000000000',
       '2022-01-02T06:00:00.000000000', '2022-01-02T07:00:00.000000000',
       '2022-01-02T08:00:00.000000000', '2022-01-02T09:00:00.000000000',
       '2022-01-02T10:00:00.000000000', '2022-01-02T11:00:00.000000000',
       '2022-01-02T12:00:00.000000000', '2022-01-02T13:00:00.000000000',
       '2022-01-02T14:00:00.000000000', '2022-01-02T15:00:00.000000000',
       '2022-01-02T16:00:00.000000000', '2022-01-02T17:00:00.000000000',
       '2022-01-02T18:00:00.000000000', '2022-01-02T19:00:00.000000000',
       '2022-01-02T20:00:00.000000000', '2022-01-02T21:00:00.000000000',
       '2022-01-02T22:00:00.000000000', '2022-01-02T23:00:00.000000000',
       '2022-01-03T00:00:00.000000000', '2022-01-03T01:00:00.000000000',
       '2022-01-03T02:00:00.000000000', '2022-01-03T03:00:00.000000000',
       '2022-01-03T04:00:00.000000000', '2022-01-03T05:00:00.000000000',
       '2022-01-03T06:00:00.000000000', '2022-01-03T07:00:00.000000000',
       '2022-01-03T08:00:00.000000000', '2022-01-03T09:00:00.000000000',
       '2022-01-03T10:00:00.000000000', '2022-01-03T11:00:00.000000000',
       '2022-01-03T12:00:00.000000000', '2022-01-03T13:00:00.000000000',
       '2022-01-03T14:00:00.000000000', '2022-01-03T15:00:00.000000000',
       '2022-01-03T16:00:00.000000000', '2022-01-03T17:00:00.000000000',
       '2022-01-03T18:00:00.000000000'], dtype='datetime64[ns]')
Dimensions without coordinates: Time
Attributes:
    description:  model times [np.datetime64]

In [14]:
wrf_t2.plot.contourf()

ValueError: DataArray must be 2d

In [ ]:
lats, lons = wrf.latlon_coords(wrf_t2)